### ISSUE TITLE
Can't run the UI App

### ISSUE THREAD

**Issue by ibrahimalakeel** [mohamedyossry22/MCQ-Exam-Angular#3]
I downloaded the App, then I ran the command `npm i`
It started installing the Dependencies, but after a while, I got this error

```
⠸ Generating browser application bundles (phase: building)...node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\Ibrahim\Desktop\programming\angular\MCQ-Exam-Angular\node_modules\webpack\lib\util\createHash.js:145:18)
    at BulkUpdateDecorator.update (C:\Users\Ibrahim\Desktop\programming\angular\MCQ-Exam-Angular\node_modules\webpack\lib\util\createHash.js:46:50)
    at OriginalSource.updateHash (C:\Users\Ibrahim\Desktop\programming\angular\MCQ-Exam-Angular\node_modules\webpack\node_modules\webpack-sources\lib\OriginalSource.js:130:8)
    at NormalModule._initBuildHash (C:\Users\Ibrahim\Desktop\programming\angular\MCQ-Exam-Angular\node_modules\webpack\lib\NormalModule.js:880:17)
    at handleParseResult (C:\Users\Ibrahim\Desktop\programming\angular\MCQ-Exam-Angular\node_modules\webpack\lib\NormalModule.js:946:10)
    at C:\Users\Ibrahim\Desktop\programming\angular\MCQ-Exam-Angular\node_modules\webpack\lib\NormalModule.js:1040:4
    at processResult (C:\Users\Ibrahim\Desktop\programming\angular\MCQ-Exam-Angular\node_modules\webpack\lib\NormalModule.js:755:11)
    at C:\Users\Ibrahim\Desktop\programming\angular\MCQ-Exam-Angular\node_modules\webpack\lib\NormalModule.js:819:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

I am using Angular 17 version

do you know, why? 
Big thanks

**Comment by ayaatef11** [comment]
I think both the two versions are not compatible so try to downgrade your version to 16 or less

**Comment by ayaatef11** [comment]
also don't forget to install angular materials
